### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by cjactivity** [EscuderoKevin/ComplexServer#1]
Hi will you help me fix especially when im creating a user using signup page.

>  Invalid address: xxxxxxxxxInvalid address: xxxxxxxxxxxSMTP Error: Could not connect to SMTP host.

I wish could donate something for you soon.

**Comment by Najsr** [comment]
You need to change the SMTP server from xxxxxxxxx to real one.

**Comment by EscuderoKevin** [comment]
Thats its , change SMTP server to real, example mail.google.com (?
